### PR TITLE
Made README.md in frontend

### PR DESCRIPTION
**Pull request by iturnmyscreenon**

### CODE REVIEW

**Comment by rocambille** [comment]
why in frontend ? (and why in src ?)

**Comment by iturnmyscreenon** [comment]
Where should i put the game's README.md ?

**Comment by rocambille** [comment]
at the root of the project :)

(to be more precise, you should complete the existing one)

**Comment by iturnmyscreenon** [comment]
Ok, noted.

**Comment by iturnmyscreenon** [comment]
README.md is corrected in the the project's root.

**Pull request merged**
